{"name": "Edit Spend", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestsSpendApi' object has no attribute 'id'", "trace": "created_spend = <tests.test_api_with_db.TestsSpendApi object at 0x0000027B85465D10>, signin_user = ('asd', 'asd')\n\n    @allure.story(\"Создание траты\")\n    def test_edit_spend(created_spend, signin_user):\n        new_amount = 1234\n        new_category = \"TestSpendCat\"\n        new_currency = \"RUB\"\n        new_description = \"TestDescriptionNew\"\n        now = datetime.now(timezone.utc)\n        spend_date = now.strftime(\"%Y-%m-%dT%H:%M:%S.%f\")[:-3] + \"Z\"\n    \n>       edit_spending(signin_user, spend_amount=new_amount, spend_category=new_category, spend_currency=new_currency, spend_date=spend_date, spend_description=new_description, spend_id=created_spend.id)\n                                                                                                                                                                                         ^^^^^^^^^^^^^^^^\nE       AttributeError: 'TestsSpendApi' object has no attribute 'id'\n\ntests\\test_api_with_db.py:51: AttributeError"}, "start": 1751800035956, "stop": 1751800035956, "uuid": "739e518d-4a5b-4d87-8d78-e4bef7ec2deb", "historyId": "be591d61314cc7394109fac6016285db", "testCaseId": "be591d61314cc7394109fac6016285db", "fullName": "tests.test_api_with_db.TestsSpendApi#test_edit_spend", "labels": [{"name": "feature", "value": "Траты"}, {"name": "story", "value": "Создание траты"}, {"name": "epic", "value": "API Niffler"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_with_db"}, {"name": "subSuite", "value": "TestsSpendApi"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "4052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_with_db"}]}