{"name": "Try Signup On Already Exsist Creds", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestsSignup' object has no attribute 'goto'", "trace": "page = <tests.test_auth.TestsSignup object at 0x0000027B8557CA50>\n\n    @allure.story(\"Попытка регистрации под существующим пользователем\")\n    def test_try_signup_on_already_exsist_creds(page: Page):\n>       page.goto(f\"{base_auth_url}register\")\n        ^^^^^^^^^\nE       AttributeError: 'TestsSignup' object has no attribute 'goto'\n\ntests\\test_auth.py:62: AttributeError"}, "start": 1751800039718, "stop": 1751800039718, "uuid": "899ca39c-1bb6-436c-88c1-16143797302c", "historyId": "8bd97c6cbbdc171e1cb34a4e720ca349", "testCaseId": "8bd97c6cbbdc171e1cb34a4e720ca349", "fullName": "tests.test_auth.TestsSignup#test_try_signup_on_already_exsist_creds", "labels": [{"name": "story", "value": "Попытка регистрации под существующим пользователем"}, {"name": "feature", "value": "Регистрация"}, {"name": "epic", "value": "Форма регистрации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestsSignup"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "4052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}