{"name": "Try Signup With Invalid Username", "status": "passed", "steps": [{"name": "Регистрируемся", "status": "passed", "parameters": [{"name": "username", "value": "'WclbicmzdLXZblXiBXcpjPQgUgrXmomQtmHDkjSRbdhOPsUMBxK'"}, {"name": "password", "value": "'h$9Q_rDf%8'"}], "start": 1751800461293, "stop": 1751800461539}], "start": 1751800461168, "stop": 1751800461539, "uuid": "8bbb291b-c0a4-454e-88f6-e49b9664a255", "historyId": "5bf71bf0cb3efa99e9ce6fbe2d86867e", "testCaseId": "5bf71bf0cb3efa99e9ce6fbe2d86867e", "fullName": "tests.test_auth.TestsSignup#test_try_signup_with_invalid_username", "labels": [{"name": "story", "value": "Попытка регистрации под невалидным именем пользователя"}, {"name": "feature", "value": "Регистрация"}, {"name": "epic", "value": "Форма регистрации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestsSignup"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "16016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}