{"name": "Try Signup With Invalid Username", "status": "passed", "steps": [{"name": "Регистрируемся", "status": "passed", "parameters": [{"name": "username", "value": "'jTdyibaAatmXZyNfoEOtGPjpOCcMvXkCkbNtDlOzigNVPCwQXaw'"}, {"name": "password", "value": "'Suv!K2MvG('"}], "start": 1751800291589, "stop": 1751800291875}], "start": 1751800291452, "stop": 1751800291875, "uuid": "8cc5b665-4329-4843-9d65-cb1fd658b2ab", "historyId": "5bf71bf0cb3efa99e9ce6fbe2d86867e", "testCaseId": "5bf71bf0cb3efa99e9ce6fbe2d86867e", "fullName": "tests.test_auth.TestsSignup#test_try_signup_with_invalid_username", "labels": [{"name": "epic", "value": "Форма регистрации"}, {"name": "feature", "value": "Регистрация"}, {"name": "story", "value": "Попытка регистрации под невалидным именем пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestsSignup"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "25556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}