{"name": "Successful Signin", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestsAuth' object has no attribute 'goto'", "trace": "page = <tests.test_auth.TestsAuth object at 0x0000027B8557C690>, create_user = ('asd', 'asd')\n\n    @allure.story(\"Успешная авторизация\")\n    def test_successful_signin(page: Page, create_user:Tuple[str, str]):\n    \n        user, password = create_user\n    \n>       page.goto(f\"{base_auth_url}login\")\n        ^^^^^^^^^\nE       AttributeError: 'TestsAuth' object has no attribute 'goto'\n\ntests\\test_auth.py:24: AttributeError"}, "start": 1751800039461, "stop": 1751800039461, "uuid": "139ef953-a3a4-4566-b164-e92232c9c556", "historyId": "1bf3ca51866d2336747b75fe09e82080", "testCaseId": "1bf3ca51866d2336747b75fe09e82080", "fullName": "tests.test_auth.TestsAuth#test_successful_signin", "labels": [{"name": "story", "value": "Успешная авторизация"}, {"name": "feature", "value": "Авторизация"}, {"name": "epic", "value": "Форма авторизации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestsAuth"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "4052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}