{"name": "Edit Spend With Error", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestsEditeSpends' object has no attribute 'reload'", "trace": "page = <tests.test_main.TestsEditeSpends object at 0x0000027B855A1950>\ncreated_spend = SpendCreate(id='d92249ee-09c0-4bb9-8164-cfc9d1a65dfe', spendDate=datetime.datetime(2025, 7, 6, 11, 7, 36, 597000, tzin...ername='asd', category=Category(id='a2b645eb-cf06-4dd4-bf66-79a50558b39d', name='why', username='asd', archived=False))\n\n    @allure.story(\"Редактирование траты с ошибкой\")\n    def test_edit_spend_with_error(page: Page, created_spend):\n    \n        now = datetime.now(timezone.utc)\n        spending_date = now.strftime(\"%Y-%m-%dT%H:%M:%S.%f\")[:-3] + \"Z\"\n    \n>       page.reload()\n        ^^^^^^^^^^^\nE       AttributeError: 'TestsEditeSpends' object has no attribute 'reload'\n\ntests\\test_main.py:113: AttributeError"}, "attachments": [{"name": "stdout", "source": "9bd33d8e-d5ec-42fb-bc21-61d8028a12fe-attachment.txt", "type": "text/plain"}], "start": 1751800056625, "stop": 1751800056625, "uuid": "85df0f24-4e48-4121-8073-7ecb45287760", "historyId": "00a1d3fff5dfa34e67a0269b1c5f64db", "testCaseId": "00a1d3fff5dfa34e67a0269b1c5f64db", "fullName": "tests.test_main.TestsEditeSpends#test_edit_spend_with_error", "labels": [{"name": "epic", "value": "Страница трат"}, {"name": "feature", "value": "Редактированиие трат"}, {"name": "story", "value": "Редактирование траты с ошибкой"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_main"}, {"name": "subSuite", "value": "TestsEditeSpends"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "4052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_main"}]}